### ISSUE TITLE
incognito mode

### ISSUE THREAD

**Issue by ilyaChuk** [kmscom/Browser-Cache-Folder-Changer#2]
First of all, thank you for such a useful program. I have moved the chrome browser cache to the ram disk. It usually works. However, when opening the browser in incognito mode, the cache files do not appear on the ram disk. Is this a problem in the program or in chrome? Is it possible to do something?

**Comment by kmscom** [comment]
Thanks for your interest in my program.
About incognito mode of Google Chrome, I found information about how it works.
- https://support.google.com/chrome/answer/9845881?hl=en#zippy=%2Chow-incognito-mode-works

According to this guide, **no data or information are saved on your device in incognito mode**. So, you may not see any files created at the new cache folder in the incognito mode.

"... In Incognito, none of your browsing history, [cookies](https://support.google.com/chrome/answer/95647) and site data, or information entered in forms are saved on your device. This means your activity doesn’t show up in your Chrome browser history, so people who also use your device won’t find your activity. ..."

To be frank, I did not consider incognito mode in designing this program.
